- Cargo.toml
- src/lib.rs
Requires a new version of `num-traits` to be pushed.
> Implement is_one and Inv for Complex.

- src/lib.rs
Resolve #3 
- Implement `Sum<Complex<T>>` and `Sum<&Complex<T>>` using `Zero` + `AddAssign`
- Implement `Product<Complex<T>>` and `Product<&Complex<T>>` using `One` + `MulAssign`
`Num` and `NumAssign` are used for type constraint.
> Implement std::iter::{Sum, Product}

- Cargo.toml
- ci/test_full.sh
- src/lib.rs
Implements #12 .
Right now it is implemented with calling `rng.gen::<T>()` for both the real and imaginary parts. I'm not 100% sure on the mathematical randomness of the distribution if the complex number is used as a vector and the angle is wanted.
As well as that, for the dependency on `rand`, I just pulled the newest version on crates.io, but it may be better to use another version. I don't have many projects that use this so I'm not sure how big of an issue this will be.
Changes:
- Optional `rand` feature and dependency on `rand`
- `impl<T> rand::Rand for Complex<T>`
> Implementing rand::Rand

- Cargo.toml
- README.md
- src/lib.rs
Based on @termoshtt's #15, without the intrusive file splitting.  I also
addressed the other review comments I had left there.  The limitations
of `no_std` are the missing implementations of `Error` and methods based
on `Float`, although `FloatCore` is now used for a few things.  Format
widths are also not supported, as I couldn't find a way to do this
without using a temporary `String`.
Fixes #6.
Closes #15.
> Add no_std support

- src/lib.rs
This avoids overflow issues with dividing by `norm_sqr`, and is
probably faster too, just for being simpler.
> Use direct ops in Rem<T> for Complex<T>

- .travis.yml
- Cargo.toml
- README.md
- build.rs
- ci/rustup.sh
- ci/test_full.sh
- src/lib.rs
The build script detects support for `u128` and `i128` (Rust 1.26+) and
enables their `Complex` implementations.  We only have to directly
implement the operators with scalar LHS, and the rest comes from
enabling num-traits' 128-bit `Num`.
> Implement 128-bit Gaussian integers

- .travis.yml
- Cargo.toml
- ci/rustup.sh
- ci/test_full.sh
- src/crand.rs
- src/lib.rs
> Update to rand 0.5

- src/crand.rs
- src/lib.rs
This lets the user create random `Complex` values using any independent
`Distribution`s for the real and imaginary parts.
> Add a generic ComplexDistribution

- src/cast.rs
- src/lib.rs
I added a submodule `cast` which defines four traits in `num-traits::cast`:
- `ToPrimitive::to_xxx` returns `None` if `im` is non-zero
- `FromPrimitive::from_xxx(a)` returns `Complex { re: T::from_xxx(a), im: T::zero() }`
- `AsPrimitive` drops the imaginary part of complex
- `NumCast` is same as `ToPrimitive`
> From/To/AsPrimitive and NumCast for Complex<T>

- src/lib.rs
Hi,
This adds the abs method for the FloatCore trait.
as far as I understand it there is no way to get the absolute value/norm of a complex number using no_std. with this method it should be possible to get absolute value with no_std.
let me know if you fine with the name abs() or want it to be norm() as pointed out in #38 
The motivation is to be able to make https://github.com/schultzer/blas-rs compile with no_std.
/edit
This is actually ["The 1-norm is simply the sum of the absolute values of the columns"](https://en.wikipedia.org/wiki/Norm_(mathematics))
> Add l1_norm() for Signed

- src/lib.rs
These use the floating point `norm()` to avoid cases where the more
generic `inv()` and `div()` might overflow in `norm_sqr()`.
Closes #23.
cc @benruijl
> Add `finv()` and `fdiv()`

- src/lib.rs
Hi Josh,
I'm not really sure with this impl I feel like I do a lot of things wrong
Right now I get it to compile and work on some tests.
But macros are not my forte.
I hope you can point me in the right direction.
Closes #37
> Add MulAdd and MulAddAssign

- src/lib.rs
- src/pow.rs
> Add Complex::powi and assorted Pow impls

- src/lib.rs
> Add a special case for sqrt of real numbers

- src/lib.rs
This also adds similar `sqrt` optimizations for imaginaries.
> Add `Complex::cbrt` for `T: Float`

- README.md
As of edition 2018, downstream crates no longer have to declare `extern crate` explicitly (especially without `#[macro_use]`).
> Removed extern crate instruction from README

- src/lib.rs
We can avoid a `self.clone()` by using more op-assign calls in place.
Fixes #50.
> Implement Mul/Div/RemAssign directly

- src/cast.rs
- src/lib.rs
Since `T: Float` also implies `T: Copy`, we don't need the indirection
of a reference for `self` or other parameters. Most of these are marked
`#[inline]` anyway, so in the end the change won't make much difference
to optimization, but it's semantically cleaner.
Users probably won't notice the change in method calls from `&self` to
`self`, but construction `from_polar` will need adjustment.
Fixes #80.
> Use values for all Float methods

- src/lib.rs
from_str_radix: Error if radix is > 18
Radix 19 and 20 introduce 'i' and 'j' as digits and this conflicts with
how complex are parsed. Before this fix, it could parse
`Num::from_str_radix("1ij + 1ij", 20)` in a pretty surprising way.
The `Num` docs already describe a rule for our situation - we might not
support every radix in our implementation; we can return an error in
this case instead.
A new (internal) error kind is introduced for this.
It is necessary to preserve the previous panicking behaviour(?) for
radix > 36 (this is what primitive types do - but other types are
allowed to do differently, including never panicking).
> Error in from_str_radix if radix > 18; avoid unfortunate interaction

- src/lib.rs
Adds a [cis function](https://en.wikipedia.org/wiki/Cis_(mathematics)) as a convenient way to construct a complex number with a specific phase/angle. Shorthand for `(Complex::i() * angle).exp()`.
> Add cis function

- Cargo.toml
- ci/test_full.sh
- src/lib.rs
`bytemuck` seems to be the *de facto* standard crate for safe
transmuting. Because `Complex<T>` is `repr(C)`, it would satisfy the
requirements for `Zeroable` and `Pod`, as long as `T` satisfies them as
well.
Add optional implemenations of `Zeroable` and `Pod`, gated behind the
`bytemuck` feature.
Closes #99
> Add support for `bytemuck` traits

- src/lib.rs
The current version of the complex exp() function is not able to handle arguments that contain +/- inf or NaN in their real or imaginary part. This impacts other complex functions that use the exp() function. 
For example, for the most widely used implementation of the complex Faddeeva function `w()`, the current `exp()` implementation leads to `w(1e160 - 1e159*i) = NaN + NaN *i` , while the correct value is  `-5.586035480670854e-162 + 5.5860354806708545e-161 * i`. The underlying reason is that the current `exp()` implementation erroneously returns  `exp(-inf + inf *i) = NaN + Nan *i` instead of the correct `0 + 0*i`.
Cf also issue #103. 
- I propose a modified complex exp() function that does deal with inf and nan. The added logic was strongly inspired by the one implemented in the …
> Adapted complex exp() function so that it can handle inf and nan arguments as well

- .github/workflows/ci.yaml
- .github/workflows/master.yaml
- .github/workflows/pr.yaml
- Cargo.toml
- README.md
- ci/rustup.sh
- ci/test_full.sh
- src/lib.rs
Earlier versions won't see the incompatible updates at all!
> Use namespaced-features to safely bump to MSRV 1.60
